### PR TITLE
Testing

### LINKED ISSUE #1: Setup project starter files

### LINKED ISSUE #7: Inventories list (with all CRUD implementation, except for 'update')

### LINKED ISSUE #8: Inventory shopping list, a shopping list, but only taking into consideration a chosen recipe and inventory

### LINKED ISSUE #10: Recipe Spec Testing

### LINKED ISSUE #11: Inventory Spec Testing

### LINKED ISSUE #12: Authorization and N+

### LINKED ISSUE #13: kanband Board Setup
Hi reviewer, In this project, we are 3 members in the group, and all task is distributed equally among each member.
Project Link: https://github.com/users/Profsain/projects/6/views/1

### PR DESCRIPTION
**Pull request by zakiyousufi**
## In this PR I have solved all errors after merging branches
@Profsain @OmarMWarraich 
Kindly fix this error in (app/views/recipe_food/edit.html.erb
error

### CODE REVIEW

**Review by Profsain — APPROVED** [review]
Thank you for your effort.
Pull request approved. You can now merge it.

**Review by OmarMWarraich — COMMENTED** [review]
@zakiyousufi @Profsain 
Everything seems to be working just fine, however, there are still a few glitches. 
1. The Add Food Button in the Inventory Foods Section leads to the foods page, however, as per my understanding of the ERD Diagram, both the foods table and inventory foods table should be separate entities in the sense that the foods table should only contain measurement unit, price and name, whereas the inventory foods table should comprise the quantity of food in the inventory and food name. I am working right now to sort this out.
2.  I will definitely look into the bug that @zakiyousufi has pointed out.

**Comment by zakiyousufi** [comment]
@OmarMWarraich 
Thanks for your kind review 
I'm witting to hear good news from you

**Comment by OmarMWarraich** [comment]
> @OmarMWarraich Thanks for your kind review I'm witting to hear good news from you

@zakiyousufi I  will now work off from your merged changes. So kindly let me finish before sending more. Saves time. :+1:

**Comment by zakiyousufi** [comment]
@OmarMWarraich 
I'm done with coding I will not push anything before your advice

**Pull request merged**
