### PR TITLE
Testing 2

### PR DESCRIPTION
**Pull request by OmarMWarraich**
@Profsain @zakiyousufi 
In this PR, I have completed the tests. Besides, I have fixed some small errors as well as implemented the logic for Shopping List.

### CODE REVIEW

**Comment by zakiyousufi** [comment]
@OmarMWarraich 
Kindly let us know what’s left

**Comment by OmarMWarraich** [comment]
> @OmarMWarraich Kindly let us know what’s left
@zakiyousufi @Profsain
OK. If nobody has approved up till now, then kindly let me finish. Or if anybody has done something, then please let us know.

**Comment by OmarMWarraich** [comment]
> > @OmarMWarraich Kindly let us know what’s left
> > @zakiyousufi @Profsain
> > OK. If nobody has approved up till now, then kindly let me finish. Or if anybody has done something, then please let us know.

@zakiyousufi @Profsain
Kindly approve. Then merge it to dev and then submit the final pr.

**Review by Profsain — APPROVED** [review]
Thank you for your contribution.
There is nothing else to say, instead is time to merge and proceed with the reviewer's request.

**Pull request merged**
